node_health_monitor_task : 
      path : tasks/node_maintenance/node_health_monitor/node_health_monitor.py
      class: NodeHealthMonitorTask
      params : 
        poolId:
          flags:
            - --poolId
          type: str
          nargs: '+'
          help: "The poolId"
        tasks:
          flags:
            - --tasks
          type: str
          nargs: '+'
          help: "The tasks"
          help1 : 1